
//SEARCH HTTP 
export const GET_HTTP_START='GET_HTTP_START';
export const GET_HTTP_USER='GET_HTTP_USER';
export const GET_HTTP_FAIL='GET_HTTP_FAIL';

//CLEAR TEXT
export const CLEAR_USER='CLEAR_USER';
export const CLEAR_USER_END='CLEAR_USER_END'

//Search
export const TEXT_VALUE='TEXT_VALUE';
export const TEXT_VALUE_END='TEXT_VALUE_END';



//User
export const USER_HTTP_START='USER_HTTP_START';
export const USER_HTTP_SUCCESS='USER_HTTP_SUCCESS';
export const USER_HTTP_FAIL='USER_HTTP_FAIL';

